# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64ressbook.proto\x12\x0csimple_proto\"\xe3\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x30\n\x06phones\x18\x04 \x03(\x0b\x32 .simple_proto.Person.PhoneNumber\x1aQ\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32\x1e.simple_proto.Person.PhoneType:\x04HOME\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"3\n\x0b\x41\x64\x64ressBook\x12$\n\x06people\x18\x01 \x03(\x0b\x32\x14.simple_proto.Person')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addressbook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERSON']._serialized_start=36
  _globals['_PERSON']._serialized_end=263
  _globals['_PERSON_PHONENUMBER']._serialized_start=137
  _globals['_PERSON_PHONENUMBER']._serialized_end=218
  _globals['_PERSON_PHONETYPE']._serialized_start=220
  _globals['_PERSON_PHONETYPE']._serialized_end=263
  _globals['_ADDRESSBOOK']._serialized_start=265
  _globals['_ADDRESSBOOK']._serialized_end=316
# @@protoc_insertion_point(module_scope)
